(function(){
'use strict';
const state={client:null,enabled:false,ready:false,config:null};
window.BILZET_BACKEND=state;
const QUEUE_KEY='bilzet-v10-sync-queue';
function queueLoad(){try{const v=JSON.parse(localStorage.getItem(QUEUE_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return []}}
function queueSave(v){localStorage.setItem(QUEUE_KEY,JSON.stringify(v))}
function queueOp(type,payload){const u=currentUser?.();if(!u)return false;const key=type+':'+String(payload.id||payload.localId||'');const q=queueLoad();if(q.some(x=>x.key===key))return true;q.push({key,type,payload,userLocalId:u.id,remoteId:u.remoteId||null,createdAt:new Date().toISOString(),attempts:0,lastError:''});queueSave(q);state.updateOfflineStatus?.();return true}
function pendingBillCount(ownerId){return queueLoad().filter(x=>x.userLocalId===ownerId&&(x.type==='invoice'||x.type==='pharmacy')).length}
state.pendingBillCount=pendingBillCount;
state.queueSize=()=>queueLoad().length;
function networkProblem(e){const m=String(e?.message||e||'').toLowerCase();return !navigator.onLine||/fetch|network|offline|timeout|failed to fetch|load failed/.test(m)}
function markInvoiceSynced(localId){try{const d=db();const i=d.invoices.find(x=>x.id===localId);if(i){i.syncStatus='synced';i.syncedAt=new Date().toISOString();save(d)}}catch{}}
function markPharmacySynced(localId){try{const u=currentUser?.();if(!u)return;const k='bilzet_pharmacy_v9_'+u.id;const d=JSON.parse(localStorage.getItem(k)||'null');if(!d)return;const sale=(d.sales||[]).find(x=>x.id===localId);if(sale){sale.syncStatus='synced';sale.syncedAt=new Date().toISOString();localStorage.setItem(k,JSON.stringify(d))}}catch{}}
async function cloudSubscription(){try{const {data:{user}}=await state.client.auth.getUser();if(!user)return null;const {data}=await state.client.from('subscriptions').select('plan_id,starts_at,expires_at,extra_bill_balance,bills_used').eq('user_id',user.id).single();return data||null}catch{return null}}
function applySubscription(sub){if(!sub)return;try{const d=db(),u=currentUser(),lu=d.users.find(x=>u&&x.id===u.id);if(!lu)return;lu.remoteBillsUsed=Number(sub.bills_used||0);lu.extraBills=Number(sub.extra_bill_balance||0);lu.plan=sub.plan_id||lu.plan;lu.planStartedAt=sub.starts_at||lu.planStartedAt;lu.planExpiresAt=sub.expires_at||lu.planExpiresAt;save(d);setRoleUI?.()}catch{}}
async function syncQueue(){if(!state.enabled||!navigator.onLine)return {ok:false,pending:queueLoad().length};let q=queueLoad();if(!q.length){state.updateOfflineStatus?.();return {ok:true,pending:0}};const keep=[];for(const op of q){try{let res;if(op.type==='invoice'){const p=op.payload;res=await state.client.rpc('register_invoice',{p_local_invoice_id:p.id,p_document_number:p.number,p_document_type:p.docType,p_invoice_date:p.date,p_total:Number(p.total||0)})}else if(op.type==='pharmacy'){const p=op.payload;res=await state.client.rpc('register_pharmacy_sale',{p_local_sale_id:p.id,p_invoice_no:p.number,p_invoice_date:p.date,p_total:Number(p.total||0),p_payload:p.cloudPayload||{}})}else continue;if(res?.error){const m=String(res.error.message||'');if(/quota|limit|expired|suspended|duplicate_document_number/.test(m)){op.lastError=m;op.blocked=true;keep.push(op);continue}if(networkProblem(res.error)){op.attempts=(op.attempts||0)+1;op.lastError=m;keep.push(op);continue}op.attempts=(op.attempts||0)+1;op.lastError=m;keep.push(op);continue}if(op.type==='invoice')markInvoiceSynced(op.payload.id);else markPharmacySynced(op.payload.id)}catch(e){op.attempts=(op.attempts||0)+1;op.lastError=String(e?.message||e);keep.push(op)}}queueSave(keep);const sub=await cloudSubscription();applySubscription(sub);state.updateOfflineStatus?.();return {ok:!keep.length,pending:keep.length}}
state.syncQueue=syncQueue;
const $id=id=>document.getElementById(id);
function notify(m){if(window.toast)window.toast(m);else alert(m)}
function note(m){const n=$id('authModeNote');if(n)n.textContent=m}
function disableAuth(disabled){['loginForm','registerForm'].forEach(id=>{const f=$id(id);if(!f)return;f.querySelectorAll('input,select,button').forEach(x=>x.disabled=disabled)})}
function clearLocalSession(){try{localStorage.removeItem(SESSION)}catch{}}
function clearLegacyAuthResidue(){try{const keys=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k)continue;if(k==='bilzet-v10-offline-verified'||k==='bilzet-v10-user-auth'||k.startsWith('bilzet-v10-user-auth-')||(/^sb-.*-auth-token$/).test(k))keys.push(k)}keys.forEach(k=>localStorage.removeItem(k));sessionStorage.removeItem('bilzet-v10-user-auth')}catch{}}
function authOnly(){if($id('appView'))$id('appView').classList.add('hidden');if($id('authView'))$id('authView').classList.remove('hidden')}
async function config(){try{const r=await fetch('/api/config',{cache:'no-store'});if(!r.ok)return null;const c=await r.json();return c?.configured&&c.supabaseUrl&&c.supabaseAnonKey?c:null}catch{return null}}
function mirror(remote,extra={}){let d=db();const email=String(remote.email||'').toLowerCase();let u=d.users.find(x=>x.remoteId===remote.id);if(!u){u={id:uid('usr'),remoteId:remote.id,name:extra.name||remote.user_metadata?.full_name||email.split('@')[0]||'BILZET User',email,role:extra.role||remote.user_metadata?.role||'business',plan:'free',businessType:extra.businessType||remote.user_metadata?.business_type||'retail',gstScheme:extra.gstScheme||remote.user_metadata?.gst_scheme||'regular',referralCode:'BZ'+Math.random().toString(36).slice(2,8).toUpperCase(),createdAt:remote.created_at||new Date().toISOString(),planStartedAt:new Date().toISOString(),planExpiresAt:addDaysISO(new Date().toISOString(),365),extraBills:0,remoteBillsUsed:0};d.users.push(u);d.settings[u.id]=defaultSettings(u)}else{u.email=email||u.email;u.name=extra.name||remote.user_metadata?.full_name||u.name;u.role=extra.role||remote.user_metadata?.role||u.role;u.businessType=extra.businessType||remote.user_metadata?.business_type||u.businessType;u.gstScheme=extra.gstScheme||remote.user_metadata?.gst_scheme||u.gstScheme}save(d);localStorage.setItem(SESSION,u.id);return u}
async function syncCloud(){if(!state.enabled)return false;const {data:{user},error:ue}=await state.client.auth.getUser();if(ue||!user)return false;const u=mirror(user);const [{data:sub,error:se},{data:plans,error:ple},{data:profile,error:pre}]=await Promise.all([state.client.from('subscriptions').select('plan_id,starts_at,expires_at,status,extra_bill_balance,bills_used').eq('user_id',user.id).maybeSingle(),state.client.from('plan_catalog').select('*').eq('active',true).order('sort_order'),state.client.from('profiles').select('full_name,role,account_status,business_type,gst_scheme').eq('id',user.id).maybeSingle()]);if(pre||se||ple){console.error('BILZET sync error',pre||se||ple);notify('Account database setup is incomplete. Run database/schema.sql in Supabase.');return false}if(profile?.account_status==='suspended'){await state.client.auth.signOut();clearLocalSession();authOnly();notify('This account is suspended. Contact BILZET support.');return false}let d=db(),lu=d.users.find(x=>x.id===u.id);if(profile){lu.name=profile.full_name||lu.name;lu.role=profile.role||lu.role;lu.businessType=profile.business_type||lu.businessType;lu.gstScheme=profile.gst_scheme||lu.gstScheme}if(sub){lu.plan=sub.plan_id||'free';lu.planStartedAt=sub.starts_at||lu.planStartedAt;lu.planExpiresAt=sub.expires_at||lu.planExpiresAt;lu.extraBills=Number(sub.extra_bill_balance||0);lu.remoteBillsUsed=Number(sub.bills_used||0)}(plans||[]).forEach(p=>{if(PLANS[p.id])Object.assign(PLANS[p.id],{name:p.display_name||PLANS[p.id].name,annual:Number(p.price_annual||0),validityDays:Number(p.validity_days||365),billLimit:p.included_bills==null?null:Number(p.included_bills),unlimitedBills:!!p.unlimited_bills,features:Array.isArray(p.features)?p.features:PLANS[p.id].features})});save(d);setRoleUI();return true}
function friendlyAuthError(error){const m=String(error?.message||'Login failed');if(/email not confirmed/i.test(m))return 'Your account is created, but email confirmation is still pending. Confirm the Supabase email, then login. For instant registration, turn Confirm email OFF in Supabase Authentication settings.';return m}
async function syncCloudSoft(){if(!navigator.onLine)return false;try{const ok=await syncCloud();if(!ok)note('Logged in. Cloud profile/plan sync needs attention; run the latest database/schema.sql in Supabase.');return ok}catch(e){console.error('BILZET cloud sync',e);note('Logged in. Cloud profile/plan sync needs attention; run the latest database/schema.sql in Supabase.');return false}}
function installAuth(){const login=$id('loginForm'),reg=$id('registerForm'),forgot=$id('forgotPasswordBtn'),logout=$id('logoutBtn');
 if(login)login.onsubmit=async e=>{e.preventDefault();const email=$id('loginEmail').value.trim().toLowerCase(),password=$id('loginPassword').value;if(!email||!password)return notify('Enter email and password');disableAuth(true);try{const {data,error}=await state.client.auth.signInWithPassword({email,password});if(error)return notify(friendlyAuthError(error));if(!data?.user||!data?.session)return notify('Login failed. Please try again.');mirror(data.user);showApp();note('Logged in securely. Refreshing or reopening BILZET will require login again.');syncCloudSoft().then(()=>syncQueue())}catch(err){console.error('BILZET login',err);notify(networkProblem(err)?'Could not reach the login service. Check internet and try again.':'Login failed. Please try again.')}finally{disableAuth(false)}};
 if(reg)reg.onsubmit=async e=>{e.preventDefault();const email=$id('regEmail').value.trim().toLowerCase(),password=$id('regPassword').value,name=$id('regName').value.trim(),role=$id('regRole').value,businessType=$id('regBusinessType').value,gstScheme=$id('regGstScheme').value;disableAuth(true);try{const {data,error}=await state.client.auth.signUp({email,password,options:{data:{full_name:name,role,business_type:businessType,gst_scheme:gstScheme}}});if(error)return notify(friendlyAuthError(error));if(!data.user)return notify('Could not create account');if(data.session){const lu=mirror(data.user,{name,role,businessType,gstScheme});showApp();note('Secure cloud account mode enabled.');notify('Welcome to BILZET');syncCloudSoft().then(()=>syncQueue())}else{clearLocalSession();authOnly();$id('loginEmail').value=email;$id('loginTab')?.click();notify('Account created. Supabase email confirmation is ON, so confirm the email first and then login. If you want registration to open BILZET immediately, turn Confirm email OFF in Supabase Authentication settings.')}}finally{disableAuth(false)}};
 if(forgot)forgot.onclick=forgotPassword;
 if(logout)logout.onclick=async()=>{try{await state.client.auth.signOut({scope:'local'})}catch(e){console.warn('BILZET sign out',e)}finally{clearLocalSession();clearLegacyAuthResidue();authOnly();location.replace('/')}};
 state.client.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT'){clearLocalSession();authOnly()}})
}
async function forgotPassword(){const email=prompt('Enter your registered email address:');if(!email)return;const {error}=await state.client.auth.signInWithOtp({email:email.trim().toLowerCase(),options:{shouldCreateUser:false}});if(error)return notify(error.message);modal(`<h3>Reset Password</h3><p class="muted">Enter the OTP sent to your email and choose a new password.</p><div class="grid2"><div><label class="label">Email OTP</label><input class="input" id="resetOtp" inputmode="numeric" maxlength="8"></div><div><label class="label">New password</label><input class="input" id="resetNewPass" type="password" minlength="8"></div></div><div class="row mt16"><button class="btn primary" id="resetPassBtn">Change Password</button><button class="btn ghost" onclick="closeModal()">Cancel</button></div>`);setTimeout(()=>{const b=$id('resetPassBtn');if(b)b.onclick=()=>verifyPasswordOtp(email)},0)}
async function verifyPasswordOtp(email){const otp=$id('resetOtp')?.value.trim(),password=$id('resetNewPass')?.value;if(!otp||!password||password.length<8)return notify('Enter OTP and a password of at least 8 characters');const {error}=await state.client.auth.verifyOtp({email:email.trim().toLowerCase(),token:otp,type:'email'});if(error)return notify(error.message);const {error:e2}=await state.client.auth.updateUser({password});if(e2)return notify(e2.message);await state.client.auth.signOut();clearLocalSession();closeModal();notify('Password changed. Login with your new password.')}
state.beforeInvoiceCommit=async inv=>{
 const u=currentUser();if(!u)return {ok:false,reason:'server'};if(planExpired(u))return {ok:false,reason:'expired'};if(!['invoice','billOfSupply'].includes(inv.docType))return {ok:true};const q=window.billQuotaInfo?.(u);if(q&&!q.unlimited&&q.remaining<=0)return {ok:false,reason:'limit'};
 const payload={id:inv.id,number:inv.number,docType:inv.docType,date:inv.date,total:Number(inv.total||0)};
 if(!state.enabled||!navigator.onLine){queueOp('invoice',payload);inv.syncStatus='pending';return {ok:true,queued:true,offline:true}}
 try{await syncCloudSoft();const {data,error}=await state.client.rpc('register_invoice',{p_local_invoice_id:payload.id,p_document_number:payload.number,p_document_type:payload.docType,p_invoice_date:payload.date,p_total:payload.total});if(error){const m=String(error.message||'');if(/quota|limit/i.test(m))return {ok:false,reason:'limit'};if(/expired/i.test(m))return {ok:false,reason:'expired'};if(/duplicate_document_number/i.test(m)){notify('Duplicate bill number blocked.');return {ok:false,reason:'duplicate'}}if(networkProblem(error)){queueOp('invoice',payload);inv.syncStatus='pending';return {ok:true,queued:true,offline:true}}notify('Bill registration failed: '+m);return {ok:false,reason:'server'}}const sub=await cloudSubscription();return {ok:true,data,subscription:sub}}
 catch(e){if(networkProblem(e)){queueOp('invoice',payload);inv.syncStatus='pending';return {ok:true,queued:true,offline:true}}console.error(e);return {ok:false,reason:'server'}}
};
state.beforePharmacySale=async sale=>{
 const u=currentUser();if(!u)return {ok:false,reason:'server'};if(planExpired(u))return {ok:false,reason:'expired'};const q=window.billQuotaInfo?.(u);if(q&&!q.unlimited&&q.remaining<=0)return {ok:false,reason:'limit'};const payload={id:sale.id,number:sale.number,date:sale.date,total:Number(sale.total||0),cloudPayload:JSON.parse(JSON.stringify(sale.cloudPayload||{}))};
 if(!state.enabled||!navigator.onLine){queueOp('pharmacy',payload);sale.syncStatus='pending';return {ok:true,queued:true,offline:true}}
 try{await syncCloudSoft();const {data,error}=await state.client.rpc('register_pharmacy_sale',{p_local_sale_id:payload.id,p_invoice_no:payload.number,p_invoice_date:payload.date,p_total:payload.total,p_payload:payload.cloudPayload});if(error){const m=String(error.message||'');if(/quota|limit/i.test(m))return {ok:false,reason:'limit'};if(/expired/i.test(m))return {ok:false,reason:'expired'};if(/duplicate_document_number/i.test(m)){notify('Duplicate pharmacy bill number blocked.');return {ok:false,reason:'duplicate'}}if(networkProblem(error)){queueOp('pharmacy',payload);sale.syncStatus='pending';return {ok:true,queued:true,offline:true}}notify('Pharmacy cloud archive failed: '+m);return {ok:false,reason:'server'}}const sub=await cloudSubscription();return {ok:true,data,subscription:sub}}
 catch(e){if(networkProblem(e)){queueOp('pharmacy',payload);sale.syncStatus='pending';return {ok:true,queued:true,offline:true}}console.error(e);return {ok:false,reason:'server'}}
};
state.requestBillPack=async()=>{closeModal();go('support');setTimeout(()=>{const s=$id('supportSubject'),m=$id('supportMessage');if(s)s.value='Buy extra 500 bills';if(m)m.value='I want to purchase an extra 500-bill pack while staying on the Free plan.'},100)};
state.renderSupport=async()=>{const box=$id('support');if(!box)return;if(!state.enabled||!navigator.onLine){box.innerHTML='<div class="card"><div class="callout">Support needs internet. Your offline bills are safe and will sync automatically when you reconnect.</div></div>';return;}box.innerHTML='<div class="card"><div class="empty">Loading support…</div></div>';const {data:{user}}=await state.client.auth.getUser();if(!user){box.innerHTML='<div class="card">Please login again.</div>';return}const {data:tickets,error}=await state.client.from('support_tickets').select('*').eq('user_id',user.id).order('created_at',{ascending:false});box.innerHTML=`<div class="grid2"><div class="card"><h3>Raise a Query</h3><label class="label">Subject</label><input class="input" id="supportSubject" placeholder="Billing / payment / account / GST"><label class="label mt12">Message</label><textarea class="textarea" id="supportMessage" placeholder="Describe the issue clearly"></textarea><button class="btn primary mt12" onclick="BILZET_BACKEND.submitSupport()">Submit Query</button></div><div class="card"><h3>Your Queries</h3>${error?`<div class="callout danger">${escapeHtml(error.message)}</div>`:(tickets||[]).map(t=>`<div class="support-thread"><div class="row"><b>${escapeHtml(t.subject)}</b><span class="badge right ${t.status==='resolved'?'ok':'gray'}">${escapeHtml(t.status)}</span></div><div class="small muted mt8">${escapeHtml(t.message)}</div>${t.admin_reply?`<div class="support-reply"><b>BILZET Support</b><br>${escapeHtml(t.admin_reply)}</div>`:''}<div class="tiny muted mt8">${new Date(t.created_at).toLocaleString()}</div></div>`).join('')||'<div class="empty">No support queries yet.</div>'}</div></div>`};
state.submitSupport=async()=>{if(!state.enabled||!navigator.onLine)return notify('Support needs internet. Reconnect and try again.');const subject=$id('supportSubject')?.value.trim(),message=$id('supportMessage')?.value.trim();if(!subject||!message)return notify('Enter subject and message');const {error}=await state.client.from('support_tickets').insert({subject,message});if(error)return notify(error.message);notify('Query submitted to BILZET support');state.renderSupport()};
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
async function init(){authOnly();clearLocalSession();clearLegacyAuthResidue();disableAuth(true);note('Checking secure BILZET login…');const cfg=await config();if(!cfg||!window.supabase){state.ready=true;authOnly();note(navigator.onLine?'Secure login is not configured. Add SUPABASE_URL and SUPABASE_ANON_KEY in Vercel, then redeploy.':'Internet is required to login.');disableAuth(!cfg||!window.supabase);return}try{state.config=cfg;state.client=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{storageKey:'bilzet-v10-4-memory-auth',persistSession:false,autoRefreshToken:true,detectSessionInUrl:false}});state.enabled=true;installAuth();state.ready=true;authOnly();disableAuth(false);note('Secure login ready. Login is required each time BILZET is opened or refreshed.')}catch(e){console.error('BILZET auth init',e);state.ready=true;state.enabled=false;clearLocalSession();clearLegacyAuthResidue();authOnly();disableAuth(true);note(navigator.onLine?'Login service failed to initialize. Check Supabase/Vercel configuration and redeploy.':'Internet is required to login.')}}
window.addEventListener('online',()=>{note('Back online — syncing pending bills…');if(!state.enabled){location.reload();return}syncQueue().then(r=>note(r.pending?`${r.pending} bill(s) still pending sync.`:'Online — all pending bills synced.'));});
window.addEventListener('offline',()=>{note('Offline mode — new bills stay safely on this device until internet returns.');state.updateOfflineStatus?.();});
init();
})();
