export const ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  CASHIER: 'CASHIER'
};

export const PRODUCT_UNITS = [
  'piece',
  'kg',
  'gram',
  'liter',
  'meter',
  'box',
  'packet',
  'dozen'
];

export const PAYMENT_METHODS = [
  'cash',
  'upi',
  'card',
  'credit',
  'mixed'
];

export const PAYMENT_STATUSES = {
  PAID: 'PAID',
  PARTIAL: 'PARTIAL',
  DUE: 'DUE'
};

export const SALE_STATUSES = {
  COMPLETED: 'COMPLETED',
  PARTIALLY_RETURNED: 'PARTIALLY_RETURNED',
  RETURNED: 'RETURNED'
};

export const STOCK_TRANSACTION_TYPES = {
  PURCHASE: 'PURCHASE',
  SALE: 'SALE',
  RETURN: 'RETURN',
  ADJUSTMENT: 'ADJUSTMENT',
  DAMAGE: 'DAMAGE',
  INITIAL: 'INITIAL'
};

export const EXPENSE_CATEGORIES = [
  'rent',
  'electricity',
  'salary',
  'transport',
  'maintenance',
  'other'
];

export const AUDIT_ACTIONS = {
  LOGIN: 'LOGIN',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  CREATE_PURCHASE: 'CREATE_PURCHASE',
  CREATE_SALE: 'CREATE_SALE',
  RETURN_SALE: 'RETURN_SALE',
  CREATE_PAYMENT: 'CREATE_PAYMENT',
  STOCK_ADJUSTMENT: 'STOCK_ADJUSTMENT',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  CREATE_CUSTOMER: 'CREATE_CUSTOMER',
  UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
  CREATE_SUPPLIER: 'CREATE_SUPPLIER',
  UPDATE_SUPPLIER: 'UPDATE_SUPPLIER',
  CREATE_EXPENSE: 'CREATE_EXPENSE',
  DELETE_RECORD: 'DELETE_RECORD'
};
